import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Undo2 } from "lucide-react"; // Import the Undo2 component correctly
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <div className="relative">
                <div className="absolute top-4 left-4 z-10 flex items-center gap-4">
                    <Link href={`/`}>
                        <Button variant="outline" className="flex items-center gap-2">
                            <Undo2 className="w-4 h-4" />
                        </Button>
                    </Link>
                </div>
                </div>
                <div className="grid min-h-screen w-full grid-cols-1 lg:grid-cols-2">
                    <div className="relative hidden lg:block bg-black">
                    </div>
                    <div className="flex items-center justify-center p-6 sm:p-12">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
